export default {
  // get todos
  GET_TODOS_PROCESSING: 'GET_TODOS_PROCESSING',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

  // add todo
  ADD_TODO_PROCESSING: 'ADD_TODO_PROCESSING',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

  // delete todo
  DELETE_TODO_PROCESSING: 'DELETE_TODO_PROCESSING',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',

  // toggle todo
  TOGGLE_TODO_PROCESSING: 'TOGGLE_TODO_PROCESSING',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  TOGGLE_TODO_FAILURE: 'TOGGLE_TODO_FAILURE'
};